version: "3"

services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: docker/data-generator
      dockerfile: Dockerfile
    container_name: data-generator
    depends_on:
      postgres:
        condition: service_healthy
    command: python data_generator.py

  minio:
    image: minio/minio:RELEASE.2023-06-09T07-32-12Z
    container_name: minio
    ports:
      - 9900:9000
      - 9901:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9901
    command: server /data/minio --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3

  bucket-creator:
    image: minio/mc:RELEASE.2023-06-06T13-48-56Z
    container_name: bucket-creator
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /usr/bin/mc config host add minio http://minio:9000 minio minio123 &&
        /usr/bin/mc mb --ignore-existing minio/bucket

networks:
  default:
    name: data-pipeline-network
